file=open("output.txt","w")
inpt1=input("Enter text to write to the file:")
file.write(inpt1+"\n")
print("Data successfully written to output.txt.\n")
file.close()

file=open("output.txt","a")
inpt2=input("Enter additional text append:")
file.write(inpt2)
print("Data successfully appended.\n")
file.close()

file=open("output.txt","r")
print("Final content of output.txt:")
line1=file.readline()
print(line1)
line2=file.readline()
print(line2,)
file.close()